# application.yml (모든 서비스의 공통 설정)
db:
  url: jdbc:postgresql://localhost:5432/trillionaires
  common:
    username: postgres
    password: postgres
    database: trillionaires
  auth:
    username: auth
    password: auth
  recruitment:
    username: recruitment
    password: recruitment
  product:
    username: product
    password: product
  review:
    username: review
    password: review
  notification:
    username: notification
    password: notification
  statistics:
    username: statistics
    password: statistics

redis:
  common:
    password: 1111
    container-port: 6379
    gui-port: 8081
  auth:
    host: localhost
    port: 16379
    gui-port: 18001
  recruitment:
    host: localhost
    port: 16380
    gui-port: 18002
  product:
    host: localhost
    port: 16381
    gui-port: 18003
  review:
    host: localhost
    port: 16382
    gui-port: 18004
  notification:
    host: localhost
    port: 16383
    gui-port: 18005
  statistics:
    host: localhost
    port: 16384
    gui-port: 18006

kafka:
  host: localhost
  port: 9092
  zookeeper-port: 2181
  ui-port: 8080

monitoring:
  prometheus:
    common-port: 9090
    auth-port: 9091
    recruitment-port: 9097
    product-port: 9093
    review-port: 9094
    notification-port: 9095
    statistics-port: 9096
  loki:
    common-port: 3100
    auth-port: 3101
    recruitment-port: 3102
    product-port: 3103
    review-port: 3104
    notification-port: 3105
    statistics-port: 3106