server:
  port: 18080

spring:
  profiles:
    active: native
  application:
    name: config-server
  config:
    import:
      - optional:file:./environment/.env[.properties]
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config-repo  # 리소스 폴더의 디렉토리 경로

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DNS_NAME}/eureka
  instance:
    prefer-ip-address: false
    hostname: ${CONFIG_DNS_NAME}
    instance-id: ${CONFIG_DNS_NAME}:${server.port}