spring:
  application:
    name: notification-service
  config:
    import: configserver:http://localhost:18080   # Config Server 주소

server:
  port: 19050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

feign:
  client:
    config:
      default:
        configuration: none  # 기본 설정 비활성화
      auth-service:
        configuration: com.trillionares.tryit.notification.libs.client.config.InternalFeignClientConfig


logging:
  level:
    root: INFO
    com.trillionares.tryit: DEBUG
    org.springframework.web: DEBUG
    feign: DEBUG
    feign.Logger: DEBUG

openapi:
  service:
    url: http://localhost:19091 # API Gateway 포트

slack:
  webhook:
    url: https://hooks.slack.com/ # 임시 가짜 URL