server:
  port: 19050

spring:
  application:
    name: notification-service
  config:
    import: configserver:${CONFIG_DNS_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: notification
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DNS_NAME}/eureka
  instance:
    prefer-ip-address: false
    hostname: ${NOTIFICATION_DNS_NAME}
    instance-id: ${NOTIFICATION_DNS_NAME}:${server.port}

feign:
  client:
    config:
      default:
        configuration: none  # 기본 설정 비활성화
      auth-service:
        configuration: com.trillionares.tryit.notification.libs.client.config.InternalFeignClientConfig

openapi:
  service:
    url: ${GATEWAY_DNS_NAME}
