spring:
  application:
    name: notification-service
  config:
    import: configserver:http://localhost:18080   # Config Server 주소
  jpa:
    hibernate:
      ddl-auto: create  # 개발 환경에서만 create 사용
    properties:
      hibernate:
        default_schema: notification
        format_sql: true
    show-sql: true

server:
  port: 19050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

feign:
  client:
    config:
      default:
        configuration: none  # 기본 설정 비활성화
      auth-service:
        configuration: com.trillionares.tryit.notification.libs.client.config.InternalFeignClientConfig

openapi:
  service:
    url: http://localhost:19091 # API Gateway 포트
