spring:
  application:
    name: statistics-service

  config:
    import: configserver:http://localhost:18080   # Config Server 주소

  datasource: # database
    url: ${DB_URL}
    username: ${DB_STATISTICS_USERNAME}
    password: ${DB_STATISTICS_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data: # redis
    redis:
      host: ${STATISTICS_REDIS_HOST}
      port: ${STATISTICS_REDIS_PORT}
      username: ${STATISTICS_REDIS_USERNAME}
      password: ${STATISTICS_REDIS_PASSWORD}

  jpa: # jpa
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      use_sql_comments: true

server:
  port: 19060

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DNS_NAME}/eureka

openapi:
  service:
   url: http://localhost:19091 # API Gateway 포트