spring:
  application:
    name: statistics-service

  config:
    import: configserver:${CONFIG_DNS_NAME}

  datasource: # database
    url: ${DB_URL}
    username: ${DB_STATISTICS_USERNAME}
    password: ${DB_STATISTICS_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data: # redis
    redis:
      host: ${STATISTICS_REDIS_HOST}
      port: ${STATISTICS_REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  jpa: # jpa
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      use_sql_comments: true

server:
  port: 19060

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DNS_NAME}/eureka
  instance:
    prefer-ip-address: false
    hostname: ${STATISTICS_DNS_NAME}
    instance-id: ${STATISTICS_DNS_NAME}

openapi:
  service:
   url: ${GATEWAY_DNS_NAME}