spring:
  application:
    name: review-service

  config:
    import: configserver:${CONFIG_DNS_NAME}

  datasource: # database
    url: ${DB_URL}
    username: ${DB_REVIEW_USERNAME}
    password: ${DB_REVIEW_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data: # redis
    redis:
      host: ${REVIEW_REDIS_HOST}
      port: ${REVIEW_REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  jpa: # jpa
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      use_sql_comments: true

server:
  port: 19040

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DNS_NAME}/eureka
  instance:
    hostname: ${REVIEW_DNS_NAME}
    nonSecurePort: 80
    nonSecurePortEnabled: true

openapi:
  service:
    url: ${GATEWAY_DNS_NAME}