server:
  port: 19091  # 게이트웨이 서비스가 실행될 포트 번호

spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  application:
    name: gateway-service  # 애플리케이션 이름을 'gateway-service'로 설정
  cloud:
    gateway:
      routes: # Spring Cloud Gateway의 라우팅 설정
        - id: auth-service           # 라우트 식별자
          uri: ${AUTH_DNS_NAME}           # 라우트 식별자
#          uri: lb://auth-service    # 'auth-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/auth/**,/users/**,/auth-service/**

        - id: product-service
          uri: ${PRODUCT_DNS_NAME}
#          uri: lb://product-service
          predicates:
            - Path=/api/products/**,/api/categories/**,/recruitments/**

        - id: review-service
          uri: ${REVIEW_DNS_NAME}
#          uri: lb://review-service
          predicates:
            - Path=/reviews/**

        - id: image-manage-service
          uri: ${IMAGE_MANAGE_DNS_NAME}
#          uri: lb://image-manage-service
          predicates:
            - Path=/api/images/**,/api/s3/**

        - id: statistics-service
          uri: ${STATISTICS_DNS_NAME}
#          uri: lb://statistics-service
          predicates:
            - Path=/statistics/**

        - id: notification-service
          uri: ${NOTIFICATION_DNS_NAME}
#          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

        - id: recruitment-service
          uri: ${TRIAL_DNS_NAME}
#          uri: lb://recruitment-service
          predicates:
            - Path=/api/submissions/**

      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정
      # CORS 설정
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DNS_NAME}/eureka

service:
  jwt:
    access-expiration: 86400000  # 24시간
    secret-key: ${SECRET_KEY} # 환경변수에서 가져옴

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true

logging:
  level:
    org.springframework.web.reactive.function.client.WebClient: DEBUG
    org.springframework.cloud.gateway: DEBUG
    com.trillionares.tryit.gateway.filter.JwtAuthFilter: DEBUG
    com.trillionares.tryit.gateway.jwt.JwtUtil: DEBUG
